export * from './accountResource.service';
import { AccountResourceService } from './accountResource.service';
export * from './atsApplicationResource.service';
import { AtsApplicationResourceService } from './atsApplicationResource.service';
export * from './atsUserResource.service';
import { AtsUserResourceService } from './atsUserResource.service';
export * from './candidateResource.service';
import { CandidateResourceService } from './candidateResource.service';
export * from './companyApplicationStatusResource.service';
import { CompanyApplicationStatusResourceService } from './companyApplicationStatusResource.service';
export * from './companyResource.service';
import { CompanyResourceService } from './companyResource.service';
export * from './companyUserResource.service';
import { CompanyUserResourceService } from './companyUserResource.service';
export * from './educationResource.service';
import { EducationResourceService } from './educationResource.service';
export * from './experienceResource.service';
import { ExperienceResourceService } from './experienceResource.service';
export * from './publicUserResource.service';
import { PublicUserResourceService } from './publicUserResource.service';
export * from './remarkResource.service';
import { RemarkResourceService } from './remarkResource.service';
export * from './userJwtController.service';
import { UserJwtControllerService } from './userJwtController.service';
export * from './userResource.service';
import { UserResourceService } from './userResource.service';
export * from './vacancyResource.service';
import { VacancyResourceService } from './vacancyResource.service';
export const APIS = [AccountResourceService, AtsApplicationResourceService, AtsUserResourceService, CandidateResourceService, CompanyApplicationStatusResourceService, CompanyResourceService, CompanyUserResourceService, EducationResourceService, ExperienceResourceService, PublicUserResourceService, RemarkResourceService, UserJwtControllerService, UserResourceService, VacancyResourceService];
