/**
 * VIBMPF App API
 * VIBMPF App API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Candidate } from './candidate';
import { CompanyApplicationStatus } from './companyApplicationStatus';
import { Vacancy } from './vacancy';
import { Remark } from './remark';


export interface AtsApplication { 
    id?: number;
    date?: string;
    remarks?: Set<Remark>;
    candidate?: Candidate;
    vacancy?: Vacancy;
    companyApplicationStatus?: CompanyApplicationStatus;
}

