/**
 * VIBMPF App API
 * VIBMPF App API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AtsUser { 
    id?: number;
    firstName?: string;
    lastName?: string;
    email?: string;
    phoneNumber?: string;
    userId?: string;
    video?: Array<string>;
    videoContentType?: string;
    cv?: Array<string>;
    cvContentType?: string;
    password?: string;
    usertype?: string;
    streetAddress?: string;
    postalCode?: string;
    city?: string;
    stateProvince?: string;
}

