/**
 * VIBMPF App API
 * VIBMPF App API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Candidate } from './candidate';
import { CompanyUser } from './companyUser';
import { AtsApplication } from './atsApplication';


export interface Remark { 
    id?: number;
    message?: string;
    date?: string;
    atsApplication?: AtsApplication;
    companyUser?: CompanyUser;
    candidate?: Candidate;
}

