/**
 * VIBMPF App API
 * VIBMPF App API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface User { 
    id?: number;
    login: string;
    firstName?: string;
    lastName?: string;
    email?: string;
    activated: boolean;
    langKey?: string;
    imageUrl?: string;
    resetDate?: string;
}

