/**
 * VIBMPF App API
 * VIBMPF App API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Company } from './company';
import { AtsApplication } from './atsApplication';


export interface Vacancy { 
    id?: number;
    name?: string;
    dateOfPosting?: string;
    description?: string;
    employmentType?: string;
    location?: string;
    video?: Array<string>;
    videoContentType?: string;
    status?: string;
    isOpen?: boolean;
    atsApplications?: Set<AtsApplication>;
    company?: Company;
}

